dark_mode: true # default: true
font: [OCR A Extended, 8] # [font name, font size]
default_column_width: 16
row_height: 32
to_display: # culumns to display for each Type, do not include name (it's required and auto included)
    Manga: {nChs: [New Chapters, max], chapter: [Current Chapter, first], tags: [Tags, first]}
    example: {nChs: [New Chapters, max], chapter: [Current Chapter, first], tags: [Tags, first]}
workers: 3
renderers: 1
hide_unupdated_works: true # default: true
hide_works_with_no_links: true # default: true
sort_by: score # defulat: score
# prettier-ignore
scores: {no Good: -1, None: 0, ok: 1, ok+: 1.1, decent: 1.5, Good: 2, Good+: 2.1, Great: 3} # numerical value of score used when sorting by score
# prettier-ignore
sites: #site,                 find,  with,                       then_find, and get,       split at, then get, render?
    manganato.com:      &001 [ul,    class: row-content-chapter, a,         href,          '-',      -1,       false]
    www.webtoons.com:   &002 [ul,    id: _listUl,                li,        id,            _,        -1,       false]
    manhuascan.com:     &003 [div,   class: list-wrap,           a,         href,          '-',      -1,       false]
    zahard.xyz:         &004 [ul,    class: chapters,            a,         href,          /,        -1,       false]
    www.royalroad.com:  &005 [table, id: chapters,               null,      data-chapters, ' ',      0,        false]
    1stkissmanga.io:    &006 [li,    class: wp-manga-chapter,    a,         href,          -|/,      -2,       false]
    comickiba.com:      &007 [li,    class: wp-manga-chapter,    a,         href,          -|/,      -2,       true]
    asura.gg:           &008 [span,  class: epcur epcurlast,     null,      null,          ' ',      1,        false]
    mangapuma.com:      &009 [div,   id: chapter-list-inner,     a,         href,          '-',      -1,       false]
    bato.to:            &010 [item,  null,                       title,     null,          ' ',      -1,       false]
    www.manga-raw.club: &011 [ul,    class: chapter-list,        a,         href,          -|/,      -4,       false]
    null: [*001, *002, *003, *004, *005, *006, *007, *008, *009, *010, *011] # for formatting reasons
    chapmanganato.com:  *001
    readmanganato.com:  *001
    nitroscans.com:     *007
    anshscans.org:      *007
    flamescans.org:     *008
    www.mcreader.net:   *011
