theme: awbreezedark # options awlight, awdark, awbreeze, awbreezedark
#test comment
font: [OCR A Extended, 8] # font name, font size
hide_unupdated_works: true # testing: comment
hide_works_with_no_links: true
sort_by: score
show_errors: false
scores:
    no Good: -1
    None: 0
    ok: 1
    ok+: 1.1
    decent: 1.5
    Good: 2
    Good+: 2.1
    Great: 3
to_display:
    Manga:
        nChs: New Chapters
        chapter: Current Chapter
        tags: Tags
default_column_width: 45
window_size: [640, 360]
total_updaters: 3
total_renderers: 1
webbrowser_executable: C:/Program Files/Google/Chrome/Application/chrome.exe
webbrowser_arg: --profile-directory="Default" "%l"
backup_directory: /backup
